export const intended_user_get: any = {
  user_id: "foo",
  user_email: "example@example.com",
  user_username: "ha",
  user_lastseen: "2021-10-19T05:24:49.115Z",
  user_datecreated: "2021-10-19T05:24:49.114Z",
  user_fullname: "Nope",
  user_bio: null,
  user_followers: [],
  user_following: [],
  user_avatar: {
    sex: "woman",
    faceColor: "#F9C9B6",
    earSize: "big",
    eyeStyle: "smile",
    noseStyle: "round",
    mouthStyle: "smile",
    shirtStyle: "short",
    glassesStyle: "none",
    hairColor: "#FC909F",
    hairStyle: "womanShort",
    hatStyle: "none",
    hatColor: "#D2EFF3",
    eyeBrowStyle: "up",
    shirtColor: "#6BD9E9",
    bgColor: "linear-gradient(45deg, #3e1ccd 0%, #ff6871 100%)",
  },
  user_streak: 0,
  user_highlight_questions: [],
  user_api_token: "ckuxn6wka0006i87ouke6wz72",
  user_twitter_handle: null,
  user_level: "None",
  user_streak_last_updated: "2021-10-19T05:24:49.114Z",
  user_streak_prev: 0,
};
